import type { Metadata } from "next";
import { Geist, Geist_Mono, Passion_One } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const passionOne = Passion_One({
  variable: "--font-passion-one",
  subsets: ["latin"],
  weight: "700",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${passionOne.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen mx-auto">
          <Header />
          <div className="flex-1 bg-cover bg-center bg-no-repeat bg-[url('/my-background.png')]">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}